deployment:
  tasks:
    # Move to the Laravel app directory
    - 'cd public_html/job-board.mechetenco.com'

    # Install dependencies for production
    - 'composer install --no-dev --optimize-autoloader'

    # Cache config, routes, views
    - 'php artisan config:cache'
    - 'php artisan route:cache'
    - 'php artisan view:cache'

    # Optional: run database migrations (use with caution)
     #- 'php artisan migrate --force'

    # Set correct permissions for storage and cache folders
    - 'chmod -R 775 storage bootstrap/cache'
